### ISSUE TITLE
git repo is 300MB

### ISSUE THREAD

**Issue by fiatjaf** [erskingardner/nostr-how#37]
Just complaining that it is taking a long time to download it from here. Maybe there are some dependencies or bundled assets committed to the git history that shouldn't be there. Would be good if we could prune them and rewrite the history.

**Comment by erskingardner** [comment]
Yeah, this bugs me too. TBH, part of using next.js was to learn more about react based frameworks. Somewhere in there I switched to yarn 2 and their newer plug and play system which bundles full dependencies instead of having everyone download their own. Kind of a strange trade-off imo.

I might have a look at doing back and doing a prune...

**Comment by fernandolguevara** [comment]
`git clone --depth 1`

**Comment by erskingardner** [comment]
Thanks for the PR @fernandolguevara – I've spent a little more time reading up on yarn's [PNP](https://yarnpkg.com/features/pnp) and [zero installs](https://yarnpkg.com/features/zero-installs) and I think I'm going to leave them in the project. Here's a [great blog post](https://medium.com/inato/make-your-ci-faster-and-improve-developer-experience-upgrade-to-yarn-2-with-or-without-939524d9bef2) that breaks down benefits and why the larger repo size is worth it. As such, I'm going to close your PR and keep the bigger repo but faster CI, etc.
